---
galaxy_info:
  company: Lightning IT
  author: Ren√© Osorio
  description: Manage OpenVPN server and client assets.
  license: GPL-3.0-only
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions: ["9"]
  galaxy_tags:
    - openvpn
    - vpn
    - networking

dependencies: []
