---
galaxy_info:
  author: Dirk Egert
  description: Day-2 operations for Vault
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: '2.18'
  role_name: vault_ops
  namespace: default
  galaxy_tags: []
dependencies: []
