galaxy_info:
  author: Dirk Egert

  description: Role to configure vault
  company: degert-it
  license: license (BSD, MIT)
  min_ansible_version: '2.8'
  role_name: vault
  namespace: default
  galaxy_tags: []
dependencies: []
