---
galaxy_info:
  author: Dirk Egert
  description: Role to configure HashiCorp Vault
  company: Lightning IT
  license: GPL-2.0-only
  min_ansible_version: "2.15"
  role_name: vault
  namespace: lit
  galaxy_tags: []

dependencies: []
