---
galaxy_info:
  role_name: nginx_config
  namespace: lit
  author: Lightning IT
  description: Manage Nginx virtual host configuration files for Podman deployment.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - nginx
    - web
    - http
    - config
    - automation

dependencies: []
