---
galaxy_info:
  role_name: coredns_deploy
  namespace: lit
  author: Ren√© Osorio
  description: Deploy CoreDNS as a Podman container with managed Corefile.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - coredns
    - dns
    - networking
    - rhel
    - automation

dependencies: []
