---
- name: Recreate vault pod
  ansible.builtin.set_fact:
    vault_config_kubeplay_remove: true
  changed_when: false

- name: Run vault pod
  ansible.builtin.set_fact:
    vault_config_kubeplay_run: true
  changed_when: false
