---
- name: assert | Test basic variables are defined
  ansible.builtin.assert:
    that:
      - vault_host_data_dir | length > 0
      - vault_cert_dir | length > 0
      - vault_config_dir | length > 0
      - vault_pod_manifest_path | length > 0
    quiet: true
  tags: always
