---
- name: Ensure core DHCP variables are set
  ansible.builtin.assert:
    that:
      - dhcp_deploy_service_name | length > 0
      - dhcp_deploy_systemd_unit_name | length > 0
      - dhcp_deploy_host_config_dir | length > 0
      - dhcp_deploy_host_config_path | length > 0
      - dhcp_deploy_host_data_dir | length > 0
      - dhcp_deploy_sysconfig_path | length > 0
    fail_msg: "DHCP core variables are missing or invalid."
  tags: always
