---
galaxy_info:
  role_name: vault_foundational
  author: Dirk Egert, Ren√© Osorio
  description: Shared Vault init-file handling tasks
  min_ansible_version: "2.15"
  license: MIT
  platforms:
    - name: EL
      versions:
        - "9"

dependencies: []
