---
galaxy_info:
  role_name: minio_ops
  namespace: lit
  author: Ren√© Osorio
  description: Day-2 operational actions for MinIO.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - minio
    - storage
    - operations
    - automation

dependencies: []
