---
# vCenter connection
manage_esxi_vcenter_hostname: ""
manage_esxi_vcenter_username: ""
manage_esxi_vcenter_password: ""
manage_esxi_validate_certs: false
manage_esxi_datacenter_name: ""
manage_esxi_cluster_name: ""
manage_esxi_license: ""

# ESXi host
manage_esxi_username: ""
manage_esxi_initial_password: ""
manage_esxi_password: ""
manage_esxi_host_password: ""
manage_esxi_hostname: ""
manage_esxi_hostname_ext: ""
manage_esxi_connection_hostname: ""
manage_esxi_domain_name: ""
manage_esxi_dns_servers: []
manage_esxi_search_domains: []
manage_esxi_mgmt_vmkernel: {}

# Host configuration
manage_esxi_options: {}
manage_esxi_services: {}
manage_esxi_portgroups: {}
manage_esxi_default_users: []

# Firewall
manage_esxi_allowed_ip_address: []
manage_esxi_allowed_ip_network: []
manage_esxi_firewall_rules: []

# Testing / stub mode
manage_esxi_stub_mode: false
