---
galaxy_info:
  role_name: sonatype_nexus
  namespace: default
  author: Dirk Egert
  description: Role to manage sonatype nexus Installation
  company: degert-it.de
  license: license (BSD, MIT)
  min_ansible_version: '2.8'
  galaxy_tags: []
dependencies: []
