---
- name: assert | Test all variable are defined
  ansible.builtin.assert:
    that:
      - vau_terraform_source is defined and vau_terraform_source | length > 0
      - vau_url | length > 0
    quiet: true
  tags: always
