---
galaxy_info:
  role_name: aap_deploy
  author: Ren√© Osorio
  company: Lightning IT
  description: Deploy AAP on RHEL.
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions: ["all"]
  galaxy_tags:
    - aap
    - automationcontroller
    - deployment

dependencies: []
