---
- name: Assert | Test config variables are defined
  ansible.builtin.assert:
    that:
      - vault_terraform_source is defined and vault_terraform_source | length > 0
      - vault_url | length > 0
    quiet: true
  tags: always
