---
- name: Ensure core Kea variables are set
  ansible.builtin.assert:
    that:
      - kea_deploy_pod_name | length > 0
      - kea_deploy_pod_manifest_path | length > 0
      - kea_deploy_image | length > 0
      - kea_deploy_container_name | length > 0
      - kea_deploy_host_config_path | length > 0
      - kea_deploy_container_config_path | length > 0
      - kea_deploy_host_data_dir | length > 0
      - kea_deploy_container_data_dir | length > 0
      - kea_deploy_dhcp4_port | int > 0
      - kea_deploy_host_dhcp4_port | int > 0
    fail_msg: "Kea core variables are missing or invalid."
  tags: always
