---
galaxy_info:
  role_name: kea_deploy
  namespace: lit
  author: Lightning IT
  description: Deploy Kea DHCP as a Podman container with managed config.
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - modulix
    - kea
    - dhcp
    - dns
    - networking
    - rhel
    - automation

dependencies: []
