---
galaxy_info:
  author: Dirk Egert
  description: Backup and restore Vault storage
  company: Lightning IT
  license: GPL-3.0-only
  min_ansible_version: '2.18'
  role_name: vault_backup_restore
  namespace: default
  galaxy_tags: []
dependencies: []
