---
- name: Ensure CoreDNS host config directories exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default(coredns_deploy_run_as_user) }}"
    group: "{{ item.group | default(coredns_deploy_run_as_group) }}"
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ coredns_deploy_host_config_dir }}"
      mode: '0755'
    - path: "{{ coredns_deploy_pod_manifest_path | dirname }}"
      owner: root
      group: root
      mode: '0755'
  when: item.path | default('') | length > 0
  tags:
    - deployment

- name: Detect SELinux status
  ansible.builtin.command: getenforce
  register: selinux_status
  changed_when: false
  failed_when: false
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - coredns_deploy_selinux_relabel | bool

- name: Render CoreDNS Corefile
  ansible.builtin.template:
    src: Corefile.j2
    dest: "{{ coredns_deploy_host_corefile_path }}"
    owner: "{{ coredns_deploy_run_as_user }}"
    group: "{{ coredns_deploy_run_as_group }}"
    mode: '0644'
  register: coredns_deploy_corefile
  notify: Reload coredns
  tags:
    - config

- name: Read SELinux context for CoreDNS mounts
  ansible.builtin.command: "ls -Z {{ item }}"
  loop:
    - "{{ coredns_deploy_host_config_dir }}"
    - "{{ coredns_deploy_host_corefile_path }}"
  register: coredns_deploy_selinux_contexts
  changed_when: false
  failed_when: false
  tags:
    - deployment
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - coredns_deploy_selinux_relabel | bool
    - selinux_status.stdout is defined
    - selinux_status.stdout != 'Disabled'
    - item | length > 0

- name: Apply SELinux context
  ansible.builtin.command: >-
    chcon -Rt container_file_t {{ coredns_deploy_selinux_relabel_targets | join(' ') }}
  register: coredns_deploy_selinux_relabel_cmd
  changed_when: coredns_deploy_selinux_type_missing | bool
  notify:
    - Recreate coredns pod
    - Run coredns pod
  tags:
    - deployment
  when:
    - ansible_distribution in ['RedHat', 'CentOS']
    - coredns_deploy_selinux_relabel | bool
    - selinux_status.stdout is defined
    - selinux_status.stdout != 'Disabled'
    - coredns_deploy_selinux_contexts is defined
    - coredns_deploy_selinux_contexts.results is defined
    - coredns_deploy_selinux_relabel_targets | length > 0
    - coredns_deploy_selinux_type_missing | bool
  vars:
    coredns_deploy_selinux_contexts_defined: >-
      {{
        coredns_deploy_selinux_contexts.results
        | selectattr('stdout', 'defined')
        | list
      }}
    coredns_deploy_selinux_type_missing: >-
      {{
        (coredns_deploy_selinux_contexts_defined
         | rejectattr('stdout', 'search', 'container_file_t')
         | list
         | length) > 0
      }}
    coredns_deploy_selinux_relabel_targets: >-
      {{
        [
          coredns_deploy_host_config_dir,
          coredns_deploy_host_corefile_path
        ]
        | reject('equalto', '')
        | list
      }}

- name: Render CoreDNS Pod manifest
  ansible.builtin.template:
    src: coredns-pod.yml.j2
    dest: "{{ coredns_deploy_pod_manifest_path }}"
    mode: '0644'
  register: coredns_deploy_pod_manifest
  notify:
    - Recreate coredns pod
    - Run coredns pod
  tags:
    - deployment

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  tags:
    - deployment
    - config

- name: Recreate coredns pod (kubeplay)
  when:
    - coredns_deploy_kubeplay_remove | default(false)
    - not coredns_deploy_skip_runtime | bool
  tags:
    - deployment
  block:
    - name: Run kubeplay remove (best effort)
      ansible.builtin.include_role:
        name: lit.foundational.kubeplay
      vars:
        kubeplay_apps: []
        kubeplay_action: remove
        kubeplay_pod_name: "{{ coredns_deploy_pod_name }}"
        kubeplay_app_name: coredns_remove
  rescue:
    - name: Ignore kubeplay remove failure
      ansible.builtin.debug:
        msg: "Skipping kubeplay remove failure."

- name: Run coredns pod (kubeplay)
  when:
    - coredns_deploy_kubeplay_run | default(false)
    - not coredns_deploy_skip_runtime | bool
  tags:
    - deployment
  block:
    - name: Run kubeplay run (best effort)
      ansible.builtin.include_role:
        name: lit.foundational.kubeplay
      vars:
        kubeplay_apps: []
        kubeplay_action: run
        kubeplay_pod_name: "{{ coredns_deploy_pod_name }}"
        kubeplay_pod_manifest_path: "{{ coredns_deploy_pod_manifest_path }}"
        kubeplay_app_name: coredns_run
  rescue:
    - name: Ignore kubeplay run failure
      ansible.builtin.debug:
        msg: "Skipping kubeplay run failure."

- name: Restart coredns pod (kubeplay)
  when:
    - coredns_deploy_kubeplay_restart | default(false)
    - not coredns_deploy_skip_runtime | bool
  tags:
    - config
  block:
    - name: Run kubeplay restart (best effort)
      ansible.builtin.include_role:
        name: lit.foundational.kubeplay
      vars:
        kubeplay_apps: []
        kubeplay_action: restart
        kubeplay_pod_name: "{{ coredns_deploy_pod_name }}"
        kubeplay_app_name: coredns_restart
  rescue:
    - name: Ignore kubeplay restart failure
      ansible.builtin.debug:
        msg: "Skipping kubeplay restart failure."
